version: '2'
services:
  vizque_apps:
    build: .
    volumes:
    - ./vizque:/VizQue/vizque
    ports:
    - "5000:5000"
    tty: true
    stdin_open: true
    privileged: true

#    /usr/sbin/python
#/usr/sbin/pip